### ISSUE TITLE
Team url is not clickable

### ISSUE THREAD

**Issue by IgorShadurin** [xssnick/Tonutils-Proxy#13]
Team url "Tonutils" is not clickable on mac m1.

<img width="329" alt="Screenshot 2023-06-14 at 10 17 33" src="https://github.com/xssnick/Tonutils-Proxy/assets/1595061/687c9cf8-43c5-4f7b-b431-b23b068683b5">

**Comment by xssnick** [comment]
Yea, there is no website yet, so not link there :D

Later will add a link. Thank you for attention :)
