### ISSUE TITLE
Unsupported protocol scheme error on nginx proxying

### ISSUE THREAD

**Issue by antonlukin** [xssnick/Tonutils-Proxy#8]
Hello and thank you for your proxy utils.
I do not really think that this error related to your app, but may be you know the solution.

I want to proxy requests to TONutlis from nginx with this code

```
location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Accept-Encoding "";
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://127.0.0.1:8080/;
    }
```

While sending requests I get the error: `unsupported protocal scheme` from this line:
https://github.com/xssnick/Tonutils-Proxy/blob/0a840bf33b405d5570c0b7a49f3982b9e524d330/internal/proxy/proxy.go#L65

It seems that nginx sends empty protocol on proxy passing.
Do we really need this checking and may be you know how to fix the problem on nginx?

**Comment by xssnick** [comment]
Hi, need to check actual request from nginx, it seems like if we will just remove this check proxy pass will not work anyway, because of empty schema

**Comment by antonlukin** [comment]
Hi, thanks for your answer.
I do not actually know how to dump request but I'm going to dive deeper into the question.

Also want to show you some links with related issues:
https://groups.google.com/g/golang-nuts/c/SbfM4lsKlEk
https://github.com/golang/go/issues/28940

May be we should respect X-Forwarded-Proto header from reverse-proxy?

**Comment by xssnick** [comment]
Thank you for info, I added support for `X-Forwarded-Proto`, you can compile from master and try. 

Or you can try using prebuilt version for linux that i compiled and attached.

[tonutils-proxy-cli-linux-amd64.zip](https://github.com/xssnick/Tonutils-Proxy/files/10545447/tonutils-proxy-cli-linux-amd64.zip)

**Comment by antonlukin** [comment]
Oh, man. It works! Thanks a lot. 
Close this issue by yourself when you think it's complete, please.
